import { GENERATOR_VERSION, GEOMETRY_VERSION, MODEL_SHA256, SCHEMA_VERSION } from "./schema.js"
export const PROTOCOL_VERSION = `${SCHEMA_VERSION}:${GENERATOR_VERSION}:${GEOMETRY_VERSION}:${MODEL_SHA256}`
