// Phase 0: Environment configuration
// Load and validate: ADMIN_INTERNAL_API_URL, MCP_TO_ADMIN_SHARED_SECRET, MCP_BEARER_TOKEN, MCP_BASE_URL
// Future: MCP_OAUTH_ISSUER_URL, MCP_OAUTH_AUDIENCE, MCP_OAUTH_CLIENT_ID, MCP_OAUTH_CLIENT_SECRET
