name: WWW Preview Deployment
on:
  push:
    branches: [staging]
jobs:
  Deploy-Preview:
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Vercel Webhook
        run: |
          set -e
          RESPONSE=$(curl -f -X POST https://api.vercel.com/v1/integrations/deploy/${{secrets.VERCEL_WWW_PROJECT_ID}}/${{secrets.VERCEL_WWW_WEBHOOK_ID}})
          echo "Vercel API Response: $RESPONSE"
